### ISSUE TITLE
NFR3. Special Animations

### ISSUE THREAD

**Issue by TKosinski24** [WSU-4110/Live-Sports-Display#10]
| NFR3.  Special Animations |
| ------------- |
| **Goal:** The display will provide special animations for target events| 
| **Stakeholders:** Clients, Providers | 
| **Description:** When a target event happens that results in an increase of the scoreboard, a key animation will be displayed on the screen for users to be notified of what happened. Depending on what event happened would result in a different animation. | 
| **Origin:** This idea came up on our second meeting together regarding what should be displayed on the screen if something like a score increase happened.  | 
| **Version:** 1.0 | 
| **Date:** 01/28/2024 | 
| **Priority:** 5 |

**Comment by MitchellBrownNE** [comment]
Probably wont be finished by the due date, and will be put on the backlog for the project. The requirement was a little ambitious to have done as it would require Jordan and Tim to create separate animations for each of players and or teams that are playing. Was not as feasible for the duration of the project.

**Comment by TKosinski24** [comment]
I added "Loading Stats", "No Stats", and "Error" to player loading animations that are dynamic
