### ISSUE TITLE
NFR4. Environment For Hardware

### ISSUE THREAD

**Issue by TKosinski24** [WSU-4110/Live-Sports-Display#11]
| NFR4.  Environment for Hardware |
| ------------- |
| **Goal:** This system will be deployed in a desired climate optimal for hardware components | 
| **Stakeholders:** Clients, Providers | 
| **Description:** When deploying finished units, the hardware will be stationed within a dry place that does not encounter any outside environmental conditions. | 
| **Origin:** This idea came up in our second meeting when discussing how this finished project would be placed and used by our clients.    | 
| **Version:** 1.0 | 
| **Date:** 01/28/2024 | 
| **Priority:** 5 |

**Comment by Grewestr** [comment]
thinking back on this, should  prompt user a good environment for optimal use on frontend UI

**Comment by TKosinski24** [comment]
Completed CAD cases for both displays.
