### ISSUE TITLE
NFR5:  Error Handling for Connection Issues

### ISSUE THREAD

**Issue by Nobody96103** [WSU-4110/Live-Sports-Display#12]
|FR1. Error Handling for Connection Issues|
|---|
|**Goal**: The system will handle connection issues when they occur.
**Stakeholders:** Clients|
| **Description:** When an error occurs, the system will continue functioning, handle the issue, and inform the customer of the issue's identity. |
| **Origin:** This requirement was thought up and properly described during the second meeting.|
| **Version:** 1.0 |
|**Date:** 1/27/2024
| **Priority:** 2 |

**Comment by MitchellBrownNE** [comment]
This function is done now and is implemented within the API

**Comment by MitchellBrownNE** [comment]
If there is a http client exception that is caught, it will print out the response code and admin must go to https://developer.sportradar.com/getting-started/docs/response-codes to determine what response code it is and what it was caused by.
