### ISSUE TITLE
NFR6: Manual input of data

### ISSUE THREAD

**Issue by AymanElfayoumi** [WSU-4110/Live-Sports-Display#15]
| NFR6: Manual input of data |
|--------|
|**Goal:** Clients should be able to bypass OCR image processing and search for data via manual text entry if they desire to do so.  |
|**Stakeholders:** Clients|
| **Description:** On the image capturing/uploading page, the UI will feature a text link that is easily visible whilst also out of the way telling the client they can click it to bypass the image capturing phase. It will bring the client to a page with text entry boxes labeled with required texts to be used to search for data. The entered text will then be used as though it had been read from the image by the OCR.  |
|**Origin:** This requirement was thought up and properly described during the second meeting.|
|**Version:** 1.0 |
|**Date:** 01/29/2024  |
|**Priority:** 2|

**Comment by MitchellBrownNE** [comment]
Function has been made and is working as intended, will return a empty string if the player typed in is not playing at the moment. Will need to get this working on the webserver side asap.

**Comment by AymanElfayoumi** [comment]
This has been implemented in results.html
