### ISSUE TITLE
FR17 OOP collaboration between OCR and API

### ISSUE THREAD

**Issue by Grewestr** [WSU-4110/Live-Sports-Display#39]
### Goal

Define a class for the players

### Description

The player class should have name, team, Boolean playing right now, maybe statistics? 

### Stakeholders

Clients, Providers

### Origin

2/23 meeting

### Priority of the proposed feature

None

**Comment by MitchellBrownNE** [comment]
Player class has been made and fully functional, player name as parameter will gather information needed for stats for player in game, if not in game will throw out a None object and will send to the webserver
