### ISSUE TITLE
FR4: Working API

### ISSUE THREAD

**Issue by Nobody96103** [WSU-4110/Live-Sports-Display#5]
|FR4. Working API|
|---|
|**Goal**: The system will request and receive live data
**Stakeholders:** Clients, Providers|
| **Description:** When the system is required to update its data, it will request the new data and receive it from the appropriate source.  |
| **Origin:** This requirement was thought up during the first meeting, and properly described during the second.|
| **Version:** 1.0 |
|**Date:** 1/27/2024
| **Priority:** 1 |

**Comment by MitchellBrownNE** [comment]
API calls have been properly working and have no issues with connections, exceptions are handled accordingly.
