### ISSUE TITLE
FR-X Fixing headers

### ISSUE THREAD

**Issue by Grewestr** [WSU-4110/Live-Sports-Display#58]
### Goal

Header link references

### Description

Please fix the header links in the html docs to navigate throughout the website

### Stakeholders

Clients, Providers

### Date

4/4/24

### Priority of the proposed feature

Must have

**Comment by MitchellBrownNE** [comment]
Headers should be fixed by now, all of the navigation bars to all of the pages work as intended.

**Comment by Nobody96103** [comment]
I'm fairly certain this is fixed - I've gone through all(?) of the links
