### ISSUE TITLE
FR5. Identifying IP Address Connected to Hardware

### ISSUE THREAD

**Issue by MitchellBrownNE** [WSU-4110/Live-Sports-Display#6]
|FR5. Identifying IP Address Connected to Hardware|
|---|
|**Goal**: The system will be able to identify the IP address connected to the hardware without issues.|
**Stakeholders:** Clients, Providers|
| **Description:** The system should be able to flawlessly detect what the IP address of the hardware that is currently connected to it. If the system is obtaining an incorrect IP address, it should display a message that the hardware has not been detected. The system will be able to display the connected hardware and be able to communicate with it. The system should allow devices to be detected for a minute and report information in 3 seconds.|
| **Origin:** Based on initial project specification document, team members came up with this description during the second meeting.|
| **Version:** 1.0 |
|**Date:** 01/28/2024
| **Priority:** 5 |

**Comment by TKosinski24** [comment]
Used PiTunnel to create a custom IP tunnel to identify specific R PI units
