### ISSUE TITLE
[BUG] parts of navigation do not funciton as intended

### ISSUE THREAD

**Issue by Nobody96103** [WSU-4110/Live-Sports-Display#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The 'home' hyperlink in stats_page does not go anywhere.
The nav bar in upload/#game-schedule is missing a home hyperlink, and the game schedule hyperlink does not go anywhere

### Expected Behavior

The 'home' hyperlinks should send the user to the home page.
The 'game schedule' hyperlinks should sent the user to the game schedule page.

### Steps To Reproduce

1. Open website
2. Click on navigation hyperlinks
3. encounter error

### Environment

```markdown
- OS: ?
- Node: ?
- npm: ?
```

### Anything else?

I know it's probably already known, but I wanted to put in a bug report to make sure it's officially reported

**Comment by Nobody96103** [comment]
I will attempt to make a fix for this on my branch

**Comment by MitchellBrownNE** [comment]
Shouldn’t be an issue, you just have to make sure you get the correct path in the URL.py file and make sure in the html file it points to it. I would refer to the home page how it goes to the stats and upload page

**Comment by Grewestr** [comment]
This is still a problem on the results.html page

**Comment by Nobody96103** [comment]
I'm pretty sure this is fixed now

**Comment by Nobody96103** [comment]
> This is still a problem on the results.html page

I can't tell where - it is that the '_game schedule_' part is meant to go to the stats page?

**Comment by MitchellBrownNE** [comment]
This is not needed to be opened as the game schedule page has been removed from the upload page.

**Comment by Nobody96103** [comment]
> This is not needed to be opened as the game schedule page has been removed from the upload page.

Should the link in results.html be both renamed and redirect to the stats page then?
