### ISSUE TITLE
FR6: Game Checker

### ISSUE THREAD

**Issue by Nobody96103** [WSU-4110/Live-Sports-Display#7]
|FR6. Game Checker|
|---|
|**Goal**: The system will not update the statistics of players when there is no game. 
**Stakeholders:** Clients, Providers|
| **Description:** The system will request information for the times that games are on. During the times when games are not on, the player statistics will not be updated. |
| **Origin:** This requirement was thought up and properly described during the second meeting.|
| **Version:** 1.0 |
|**Date:** 1/28/2024
| **Priority:** 4 |

**Comment by MitchellBrownNE** [comment]
Just had made an error handling when game that is asked for if it comes back with response code 404, it will return the empty list and print that the specific player is not playing today.
