### ISSUE TITLE
1pX9.gif in templates

### ISSUE THREAD

**Issue by Nobody96103** [WSU-4110/Live-Sports-Display#76]
The file _1pX9.gif_ is in both _LiveStats/static_ and _LiveStats/templates_.
We can remove it from templates, right?

**Comment by Nobody96103** [comment]
Same with _MMM_logo.png_

**Comment by Grewestr** [comment]
Im not sure, i think we should be fine?

**Comment by Nobody96103** [comment]
> Im not sure, i think we should be fine?

Yeah, nothing uses them - I'll delete them
